spring.application.name=productcommand
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/seguridad_db?createDatabaseIfNotExist=true
spring.datasource.username=user
spring.datasource.password=prueba123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.cloud.function.definition=handlerCommands;handleClients
spring.cloud.stream.bindings.handlerCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handlerCommands-in-0.content-type=application/json
spring.cloud.stream.bindings.handlerCommands-in-0.group=products-command
spring.cloud.stream.kafka.bindings.handlerCommands-in-0.consumer.start-offset=latest
spring.cloud.stream.kafka.binder.brokers=localhost:9092


spring.cloud.stream.bindings.handleClients-in-0.destination=clients.commands
spring.cloud.stream.bindings.handleClients-in-0.content-type=application/json
spring.cloud.stream.bindings.handleClients-in-0.group=clients-command



spring.cloud.stream.bindings.handlerCommands-out-0.destination=products.replies
spring.cloud.stream.bindings.handlerCommands-out-o.content-type=aplication/json


## Security JWT
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#jwt.expiration=86400000


